manifest:
  remotes:
    - name: zmkfirmware
      url-base: https://github.com/zmkfirmware
    - name: urob
      url-base: https://github.com/urob
  projects:
    - name: zmk
      remote: urob
      revision: main  # Nutze 'main' für urob's aktuelle Version inkl. Maus-Support
      import: app/west.yml
  self:
    path: config
