name: Build ZMK Firmware
on: [push, pull_request, workflow_dispatch]

jobs:
  build:
    runs-on: ubuntu-latest
    container:
      image: zmkfirmware/zmk-build-arm:stable
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Initialize Workspace
        run: |
          # Wir erzwingen den Pfad zum Workspace, um die west.yml sicher zu finden
          west init -l "${{ github.workspace }}"
          west update
          west zephyr-export

      - name: Build Left Side
        run: |
          west build -s zmk/app -d "/tmp/left" -b "nice_nano_v2" -- \
          -DSHIELD="sofle_choc_pro_left" \
          -DZMK_CONFIG="${{ github.workspace }}/config" \
          -DZMK_EXTRA_MODULES="${{ github.workspace }}"

      - name: Build Right Side
        run: |
          west build -s zmk/app -d "/tmp/right" -b "nice_nano_v2" -- \
          -DSHIELD="sofle_choc_pro_right" \
          -DZMK_CONFIG="${{ github.workspace }}/config" \
          -DZMK_EXTRA_MODULES="${{ github.workspace }}"

      - name: Archive artifacts
        uses: actions/upload-artifact@v4
        with:
          name: firmware
          path: |
            /tmp/left/zephyr/zmk.uf2
            /tmp/right/zephyr/zmk.uf2
