name: Build ZMK Firmware
on:
  push:
    branches: [ main, ModernCode ]
  pull_request:
    branches: [ main, ModernCode ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    name: Build Left Side
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: Install West
        run: pip install west

      - name: Cache west modules
        uses: actions/cache@v4
        env:
          cache-name: cache-zephyr-modules
        with:
          path: |
            modules
            tools
            zephyr
            bootloader
            zmk
          key: ${{ runner.os }}-build-${{ env.cache-name }}-${{ hashFiles('**/west.yml') }}

      - name: Initialize workspace
        run: |
          west init -l config
          west update
          west zephyr-export

      - name: West Build
        run: |
          west build -s zmk/app -d "/tmp/tmp.left" -b "sofle_choc_pro_left" -- \
          -DZMK_CONFIG="${{ github.workspace }}/config" \
          -DZEPHYR_EXTRA_MODULES="${{ github.workspace }}" \
          -DBOARD_ROOT="${{ github.workspace }}" \
          -DSHIELD="sofle_choc_pro_left"

      - name: Archive artifacts
        uses: actions/upload-artifact@v4
        with:
          name: firmware
          path: /tmp/tmp.left/zephyr/zmk.uf2
